name: responsive
description: "A Flutter package for building responsive UIs using LayoutBuilder with performance optimization"
version: 0.0.1
homepage: https://github.com/Tinalexman/responsive

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
